version: '3.9'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "$HOME/.posgres:/var/lib/postgresql/data/pgdata"
    ports:
      - "${DB_PORT}:5432"
#  backend:
#    build:
#      context: "."
#      dockerfile: ./build/go/Dockerfile
#    command: ["/opt/app/app"]
#    ports:
#      - "8000:5000"
#  frontend:
#    build:
#      context: "."
#      dockerfile: ./build/frontend/Dockerfile
#    command: [ "nginx", "-g", "daemon off;" ]
#    ports:
#      - "8000:5000"
